package me.waveio.claudebot.ui

import me.waveio.claudebot.state.Preferences
import me.waveio.claudebot.state.Screen

interface AppActions {
    fun connect()
    fun navigate(screen: Screen)
    fun newChat()
    fun openChat(id: String)
    fun menu(open: Boolean)
    fun modelPicker(open: Boolean)
    fun selectModel(id: String)
    fun selectEffort(value: String)
    fun draft(value: String)
    fun send(delivery: String = "queue", scheduledAt: String? = null)
    fun stop()
    fun resumeQueue()
    fun cancelPending(id: String)
    fun retryPending(id: String)
    fun sendModes(open: Boolean)
    fun schedule(open: Boolean)
    fun attachments(open: Boolean)
    fun pickFile(kind: String)
    fun removeAttachment(path: String)
    fun previewAttachment(path: String)
    fun closePreview()
    fun startDictation()
    fun stopDictation()
    fun cancelDictation()
    fun useTranscript()
    fun copyMessage(id: String)
    fun shareMessage(id: String)
    fun editMessage(id: String)
    fun cancelEdit()
    fun regenerate(id: String)
    fun search(value: String)
    fun openDirectory(path: String)
    fun openFile(path: String)
    fun closeFile()
    fun fileText(value: String)
    fun retryFileSave()
    fun preferences(value: Preferences)
    fun resetWallpaper()
    fun requestNotifications()
    fun profileName(value: String)
    fun profilePersona(value: String)
    fun saveProfile()
    fun disconnect()
    fun dismissNotice()
    fun offlineDelivery(allow: Boolean)
    fun refresh()
}
